### PR TITLE
Updated Buildroot CI to make it work with autotools.

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**

### CODE REVIEW

**Comment by enaess** [comment]
@RICCIARDI-Adrien - In your buildroot environment, just a s a precaution, but what does the output of running 

LD_TRACE_LOADED_OBJECTS=1 ./pppd

Just wanted to make sure it links to the openssl, libpcap and others in the staging directory. You may need to chroot to the staging directory to do this or setup the LD_LIBRARY_PATH="$stagingdir:/path/to/usr/lib:etc"

**Comment by RICCIARDI-Adrien** [comment]
Great !
I hope that autotools will be adopted, they will greatly improve PPP maintenance in the wild.
If Buildroot maintainers do not have the time to update PPP, I might submit some patches to do that. However, I will need some explanations on some changes to make sure that they won't break a particular board configuration.

**Comment by RICCIARDI-Adrien** [comment]
I built a Buildroot image for the Raspberry Pi 4 and ran `pppd` on it.
Here are the test results :
```
# ldd /usr/sbin/pppd
	libpcap.so.1 => /usr/lib//libpcap.so.1 (0xb6ef4000)
	libssl.so.1.1 => /usr/lib//libssl.so.1.1 (0xb6e7f000)
	libcrypto.so.1.1 => /usr/lib//libcrypto.so.1.1 (0xb6c8b000)
	libc.so.0 => /lib//libc.so.0 (0xb6bfd000)
	libatomic.so.1 => /lib//libatomic.so.1 (0xb6be8000)
	ld-uClibc.so.1 => /lib/ld-uClibc.so.0 (0xb6f39000)
```
`LD_TRACE_LOADED_OBJECTS=1 /usr/sbin/pppd` gives the same result than above.

Basic `pppd` run :
```
# pppd --help
pppd version 2.4.10
Usage: pppd [ options ], where options are:
	<device>	Communicate over the named device
	<speed>		Set the baud rate to <speed>
	<loc>:<rem>	Set the local and/or remote interface IP
			addresses.  Either one may be omitted.
	asyncmap <n>	Set the desired async map to hex <n>
	auth		Require authentication from peer
        connect <p>     Invoke shell command <p> to set up the serial line
	crtscts		Use hardware RTS/CTS flow control
	defaultroute	Add default route through interface
	file <f>	Take options from file <f>
	modem		Use modem control lines
	mru <n>		Set MRU value to <n> for negotiation
See pppd(8) for more options.
```

Do you want me to test some other things ?

**Comment by enaess** [comment]
Looks good. The autotools change is a large one, and I would imagine maintainers would be hesitant to adopt it. However, given the enthusiasm from the community of maintainers, I'd say there might be a "slight" chance :)

**Pull request merged**
